apiVersion: v1
kind: Service
metadata:
  name: natours
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8099
    nodePort: 31091
  selector:
    app: natours
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: natours
spec:
  replicas: 1
  selector:
    matchLabels:
      app: natours
  template:
    metadata:
      labels:
        app: natours
    spec:
      containers:
      - name: natours
        image: ${{FD_PROJECT_DOCKER_IMAGE_NAME}}
        ports:
        - containerPort: 8099
